-- HarmonizeIQ Seed Data
-- Run after schema.sql to populate demo data

-- Insert Source Systems (Retailers)
INSERT INTO source_systems (id, code, name, type, is_active) VALUES
    (uuid_generate_v4(), 'WALMART', 'Walmart US', 'retailer', true),
    (uuid_generate_v4(), 'TARGET', 'Target', 'retailer', true),
    (uuid_generate_v4(), 'KROGER', 'Kroger', 'retailer', true),
    (uuid_generate_v4(), 'COSTCO', 'Costco Wholesale', 'retailer', true),
    (uuid_generate_v4(), 'CVS', 'CVS Pharmacy', 'retailer', true)
ON CONFLICT (code) DO NOTHING;

-- Insert Categories
INSERT INTO categories (id, name, level) VALUES
    (uuid_generate_v4(), 'Oral Care', 1),
    (uuid_generate_v4(), 'Beverages', 1),
    (uuid_generate_v4(), 'Personal Care', 1),
    (uuid_generate_v4(), 'Household', 1),
    (uuid_generate_v4(), 'Snacks', 1)
ON CONFLICT DO NOTHING;

-- Insert Brands
INSERT INTO brands (id, name, manufacturer, aliases) VALUES
    (uuid_generate_v4(), 'Crest', 'P&G', '["Procter & Gamble", "P&G"]'),
    (uuid_generate_v4(), 'Colgate', 'Colgate-Palmolive', '["CP"]'),
    (uuid_generate_v4(), 'Sensodyne', 'GSK', '["GlaxoSmithKline"]'),
    (uuid_generate_v4(), 'Oral-B', 'P&G', '["Procter & Gamble"]'),
    (uuid_generate_v4(), 'Pepsi', 'PepsiCo', '["Pepsi Co"]'),
    (uuid_generate_v4(), 'Coca-Cola', 'Coca-Cola Company', '["Coke", "TCCC"]'),
    (uuid_generate_v4(), 'Mountain Dew', 'PepsiCo', '["MTN DEW"]'),
    (uuid_generate_v4(), 'Sprite', 'Coca-Cola Company', '[]'),
    (uuid_generate_v4(), 'Head & Shoulders', 'P&G', '["H&S"]'),
    (uuid_generate_v4(), 'Pantene', 'P&G', '[]'),
    (uuid_generate_v4(), 'Dove', 'Unilever', '["UL"]'),
    (uuid_generate_v4(), 'Old Spice', 'P&G', '["OS"]'),
    (uuid_generate_v4(), 'Tide', 'P&G', '["TD"]'),
    (uuid_generate_v4(), 'Gain', 'P&G', '[]'),
    (uuid_generate_v4(), 'Dawn', 'P&G', '[]'),
    (uuid_generate_v4(), 'Lay''s', 'PepsiCo', '["Lays", "Frito-Lay"]'),
    (uuid_generate_v4(), 'Doritos', 'PepsiCo', '["Frito-Lay"]'),
    (uuid_generate_v4(), 'Gatorade', 'PepsiCo', '["GAT"]'),
    (uuid_generate_v4(), 'Aquafina', 'PepsiCo', '[]'),
    (uuid_generate_v4(), 'Listerine', 'Johnson & Johnson', '["J&J"]')
ON CONFLICT DO NOTHING;

-- Insert Demo User
INSERT INTO users (id, email, password_hash, name, role, is_active) VALUES
    (uuid_generate_v4(), 'admin@harmonizeiq.com', '$2b$10$placeholder_hash', 'Admin User', 'admin', true),
    (uuid_generate_v4(), 'reviewer@harmonizeiq.com', '$2b$10$placeholder_hash', 'Data Steward', 'reviewer', true)
ON CONFLICT (email) DO NOTHING;

-- Sample Manufacturer Catalog entries (Golden Record)
-- These would normally be loaded from the CSV generated by mock data script
DO $$
DECLARE
    brand_crest_id UUID;
    brand_colgate_id UUID;
    brand_pepsi_id UUID;
    brand_tide_id UUID;
    brand_lays_id UUID;
    brand_hs_id UUID;
    cat_oral_id UUID;
    cat_bev_id UUID;
    cat_household_id UUID;
    cat_snacks_id UUID;
    cat_personal_id UUID;
BEGIN
    -- Get brand IDs
    SELECT id INTO brand_crest_id FROM brands WHERE name = 'Crest' LIMIT 1;
    SELECT id INTO brand_colgate_id FROM brands WHERE name = 'Colgate' LIMIT 1;
    SELECT id INTO brand_pepsi_id FROM brands WHERE name = 'Pepsi' LIMIT 1;
    SELECT id INTO brand_tide_id FROM brands WHERE name = 'Tide' LIMIT 1;
    SELECT id INTO brand_lays_id FROM brands WHERE name = 'Lay''s' LIMIT 1;
    SELECT id INTO brand_hs_id FROM brands WHERE name = 'Head & Shoulders' LIMIT 1;
    
    -- Get category IDs
    SELECT id INTO cat_oral_id FROM categories WHERE name = 'Oral Care' LIMIT 1;
    SELECT id INTO cat_bev_id FROM categories WHERE name = 'Beverages' LIMIT 1;
    SELECT id INTO cat_household_id FROM categories WHERE name = 'Household' LIMIT 1;
    SELECT id INTO cat_snacks_id FROM categories WHERE name = 'Snacks' LIMIT 1;
    SELECT id INTO cat_personal_id FROM categories WHERE name = 'Personal Care' LIMIT 1;

    -- Insert sample products
    INSERT INTO manufacturer_catalog (id, gtin, canonical_name, brand_id, category_id, size_value, size_unit, size_normalized_ml, is_active)
    VALUES
        (uuid_generate_v4(), '012345678901', 'Crest 3D White Radiant Mint 4.8oz', brand_crest_id, cat_oral_id, 4.8, 'oz', 141.95, true),
        (uuid_generate_v4(), '012345678902', 'Crest Pro-Health Clean Mint 4.6oz', brand_crest_id, cat_oral_id, 4.6, 'oz', 136.04, true),
        (uuid_generate_v4(), '012345678903', 'Colgate Total Whitening 5.1oz', brand_colgate_id, cat_oral_id, 5.1, 'oz', 150.82, true),
        (uuid_generate_v4(), '012345678904', 'Pepsi Original 2000ml', brand_pepsi_id, cat_bev_id, 2000, 'ml', 2000, true),
        (uuid_generate_v4(), '012345678905', 'Tide PODS Original 42ct', brand_tide_id, cat_household_id, 42, 'ct', 42, true),
        (uuid_generate_v4(), '012345678906', 'Lay''s Classic 10oz', brand_lays_id, cat_snacks_id, 10, 'oz', 283.5, true),
        (uuid_generate_v4(), '012345678907', 'Head & Shoulders Classic Clean 400ml', brand_hs_id, cat_personal_id, 400, 'ml', 400, true)
    ON CONFLICT DO NOTHING;
END $$;

-- Log completion
DO $$
BEGIN
    RAISE NOTICE 'HarmonizeIQ seed data loaded successfully!';
END $$;
